Flickr:
  Photogallery:
    templateRootPath: 'resource://Flickr.Photogallery/Private/Templates/'
    apiKey: '7fd8a37ae675f681e1013a59f2fc8d5f'
    lightbox: 'MagnificPopup'
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Flickr.Photogallery:
            - Main
            - 'NodeTypes/*'
      defaultLanguage: 'de'
    nodeTypes:
      groups:
        flickr:
          position: 'end'
          label: 'Flickr'
    fusion:
      autoInclude:
        Flickr.Photogallery: true
  Flow:
    i18n:
      defaultLocale: de